CREATE TYPE "public"."account_type_enum" AS ENUM('asset', 'liability', 'equity', 'income', 'expense');--> statement-breakpoint
CREATE TYPE "public"."contribution_category_enum" AS ENUM('member', 'group', 'district', 'service', 'congregation');--> statement-breakpoint
CREATE TYPE "public"."line_dc" AS ENUM('debit', 'credit');--> statement-breakpoint
CREATE TYPE "public"."normal_balance_enum" AS ENUM('debit', 'credit');--> statement-breakpoint
CREATE TYPE "public"."payment_method_enum" AS ENUM('cash', 'mpesa', 'bank', 'cheque');--> statement-breakpoint
CREATE TYPE "public"."session_type_enum" AS ENUM('auth', 'password_reset');--> statement-breakpoint
CREATE TYPE "public"."user_type_enum" AS ENUM('super admin', 'admin', 'standard user');--> statement-breakpoint
CREATE TABLE "congregations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "congregations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"parish_name" varchar(255),
	"congregation_name" varchar(255) NOT NULL,
	"contact" varchar(15),
	"email" varchar(255),
	"address" varchar(255),
	"about_us" varchar(255),
	"is_parish" boolean DEFAULT false,
	"prefix" varchar(50),
	"inauguration_date" date,
	"sactuary_type" varchar(15),
	"year_started" integer,
	"foundation_stone" date,
	"dedication_date" date,
	"deleted_at" timestamp,
	CONSTRAINT "congregations_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
CREATE TABLE "districts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "districts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"district_name" varchar(255) NOT NULL,
	"deleted_at" timestamp,
	"congregation_id" integer NOT NULL,
	CONSTRAINT "districts_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
CREATE TABLE "fiscal_years" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fiscal_years_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"year_name" text NOT NULL,
	"start_date" date NOT NULL,
	"end_date" date NOT NULL,
	"closed" boolean DEFAULT false NOT NULL,
	"created_date" date NOT NULL,
	"closed_date" date,
	"prefix_references" boolean DEFAULT false NOT NULL,
	"deleted_at" timestamp,
	CONSTRAINT "fiscal_years_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
CREATE TABLE "groups" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"group_name" text NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"deleted_at" timestamp,
	"congregation_id" integer NOT NULL,
	CONSTRAINT "groups_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
CREATE TABLE "journal_entries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "journal_entries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"transaction_date" date NOT NULL,
	"line_number" integer NOT NULL,
	"account_id" integer NOT NULL,
	"dc" "line_dc" NOT NULL,
	"amount" numeric(18, 2) NOT NULL,
	"memo" text,
	"reference" varchar(255),
	"source" varchar(255),
	"source_id" varchar(255),
	"journal_no" integer,
	"congregation_id" integer,
	"deleted_at" timestamp,
	CONSTRAINT "journal_entries_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
CREATE TABLE "ledger_accounts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ledger_accounts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(255) NOT NULL,
	"account_type" "account_type_enum" NOT NULL,
	"parent_id" integer,
	"description" varchar(255),
	"is_bank" boolean DEFAULT false NOT NULL,
	"account_no" varchar(100),
	"for_group" boolean DEFAULT false NOT NULL,
	"is_posting" boolean DEFAULT false NOT NULL,
	"normal_balance" "normal_balance_enum" NOT NULL,
	"is_editable" boolean DEFAULT true NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"congregation_id" integer,
	"deleted_at" timestamp,
	CONSTRAINT "ledger_accounts_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
CREATE TABLE "receipt_details" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "receipt_details_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"header_id" integer NOT NULL,
	"contribution_account_id" integer NOT NULL,
	"payment_method" "payment_method_enum" NOT NULL,
	"bank_id" integer,
	"amount" numeric(18, 2) NOT NULL,
	"category" "contribution_category_enum" NOT NULL,
	"contributor_member_id" integer,
	"contributor_group_id" integer,
	"contributor_district_id" integer,
	"contributor_service_id" integer,
	"contributor_congregation_id" integer,
	"payment_reference" varchar(255),
	"narration" varchar(50),
	"income_type" integer DEFAULT 1 NOT NULL,
	"for_group" boolean DEFAULT false NOT NULL,
	"sub_account_id" integer,
	CONSTRAINT "receipt_details_one_contributor_check" CHECK ((
				(CASE WHEN "receipt_details"."contributor_member_id" IS NOT NULL THEN 1 ELSE 0 END) +
				(CASE WHEN "receipt_details"."contributor_group_id" IS NOT NULL THEN 1 ELSE 0 END) +
				(CASE WHEN "receipt_details"."contributor_district_id" IS NOT NULL THEN 1 ELSE 0 END) +
				(CASE WHEN "receipt_details"."contributor_service_id" IS NOT NULL THEN 1 ELSE 0 END) +
				(CASE WHEN "receipt_details"."contributor_congregation_id" IS NOT NULL THEN 1 ELSE 0 END)
			) = 1)
);
--> statement-breakpoint
CREATE TABLE "receipt_header" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "receipt_header_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"receipt_no" varchar(15) NOT NULL,
	"contribution_date" date NOT NULL,
	"posted_by" integer NOT NULL,
	"congregation_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp,
	CONSTRAINT "receipt_header_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
CREATE TABLE "roles" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "roles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"role_name" varchar(100) NOT NULL,
	"deleted_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "services" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "services_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar NOT NULL,
	"service_time" varchar NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"deleted_at" timestamp,
	"congregation_id" integer NOT NULL,
	CONSTRAINT "services_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer,
	"type" "session_type_enum" NOT NULL,
	"token_hash" varchar(255),
	"expires_at" timestamp NOT NULL,
	"last_accessed_at" timestamp,
	"remember_me" boolean DEFAULT false NOT NULL,
	"ip_address" varchar(255),
	"user_agent" varchar(512),
	"data" jsonb NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sub_accounts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sub_accounts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar NOT NULL,
	"bank_id" integer,
	"account_id" integer,
	"group_id" integer,
	"district_id" integer,
	"deleted_at" timestamp,
	CONSTRAINT "sub_accounts_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar(100) NOT NULL,
	"user_name" varchar(255) NOT NULL,
	"user_type" "user_type_enum" DEFAULT 'standard user' NOT NULL,
	"password" varchar(255) NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"contact" varchar(15),
	"district_id" integer,
	"congregation_id" integer NOT NULL,
	"role_id" integer,
	"transfer_id" integer,
	"last_login" timestamp,
	"login_attempt_count" integer DEFAULT 0 NOT NULL,
	"login_locked_until" timestamp,
	"password_reset_code_hash" varchar(255),
	"password_reset_code_expires_at" timestamp,
	"password_reset_code_sent_at" timestamp,
	"password_reset_attempt_count" integer DEFAULT 0 NOT NULL,
	"password_reset_locked_until" timestamp,
	CONSTRAINT "users_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
ALTER TABLE "districts" ADD CONSTRAINT "districts_congregation_id_congregations_id_fk" FOREIGN KEY ("congregation_id") REFERENCES "public"."congregations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "groups" ADD CONSTRAINT "groups_congregation_id_congregations_id_fk" FOREIGN KEY ("congregation_id") REFERENCES "public"."congregations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "journal_entries" ADD CONSTRAINT "journal_entries_account_id_ledger_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."ledger_accounts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "journal_entries" ADD CONSTRAINT "journal_entries_congregation_id_congregations_id_fk" FOREIGN KEY ("congregation_id") REFERENCES "public"."congregations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ledger_accounts" ADD CONSTRAINT "ledger_accounts_congregation_id_congregations_id_fk" FOREIGN KEY ("congregation_id") REFERENCES "public"."congregations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "receipt_details" ADD CONSTRAINT "receipt_details_header_id_receipt_header_id_fk" FOREIGN KEY ("header_id") REFERENCES "public"."receipt_header"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "receipt_details" ADD CONSTRAINT "receipt_details_contribution_account_id_ledger_accounts_id_fk" FOREIGN KEY ("contribution_account_id") REFERENCES "public"."ledger_accounts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "receipt_details" ADD CONSTRAINT "receipt_details_bank_id_ledger_accounts_id_fk" FOREIGN KEY ("bank_id") REFERENCES "public"."ledger_accounts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "receipt_details" ADD CONSTRAINT "receipt_details_contributor_group_id_groups_id_fk" FOREIGN KEY ("contributor_group_id") REFERENCES "public"."groups"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "receipt_details" ADD CONSTRAINT "receipt_details_contributor_district_id_districts_id_fk" FOREIGN KEY ("contributor_district_id") REFERENCES "public"."districts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "receipt_details" ADD CONSTRAINT "receipt_details_contributor_service_id_services_id_fk" FOREIGN KEY ("contributor_service_id") REFERENCES "public"."services"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "receipt_details" ADD CONSTRAINT "receipt_details_contributor_congregation_id_congregations_id_fk" FOREIGN KEY ("contributor_congregation_id") REFERENCES "public"."congregations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "receipt_details" ADD CONSTRAINT "receipt_details_sub_account_id_sub_accounts_id_fk" FOREIGN KEY ("sub_account_id") REFERENCES "public"."sub_accounts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "receipt_header" ADD CONSTRAINT "receipt_header_posted_by_users_id_fk" FOREIGN KEY ("posted_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "receipt_header" ADD CONSTRAINT "receipt_header_congregation_id_congregations_id_fk" FOREIGN KEY ("congregation_id") REFERENCES "public"."congregations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "services" ADD CONSTRAINT "services_congregation_id_congregations_id_fk" FOREIGN KEY ("congregation_id") REFERENCES "public"."congregations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sub_accounts" ADD CONSTRAINT "sub_accounts_bank_id_ledger_accounts_id_fk" FOREIGN KEY ("bank_id") REFERENCES "public"."ledger_accounts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sub_accounts" ADD CONSTRAINT "sub_accounts_account_id_ledger_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."ledger_accounts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sub_accounts" ADD CONSTRAINT "sub_accounts_group_id_groups_id_fk" FOREIGN KEY ("group_id") REFERENCES "public"."groups"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sub_accounts" ADD CONSTRAINT "sub_accounts_district_id_districts_id_fk" FOREIGN KEY ("district_id") REFERENCES "public"."districts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_district_id_districts_id_fk" FOREIGN KEY ("district_id") REFERENCES "public"."districts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_congregation_id_congregations_id_fk" FOREIGN KEY ("congregation_id") REFERENCES "public"."congregations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_role_id_roles_id_fk" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "congregations_congregation_name_idx" ON "congregations" USING btree ("congregation_name");--> statement-breakpoint
CREATE INDEX "congregations_prefix_idx" ON "congregations" USING btree ("prefix");--> statement-breakpoint
CREATE INDEX "districts_congregation_id_idx" ON "districts" USING btree ("congregation_id");--> statement-breakpoint
CREATE INDEX "districts_district_name_idx" ON "districts" USING btree ("district_name");--> statement-breakpoint
CREATE UNIQUE INDEX "districts_congregation_id_district_name_unique" ON "districts" USING btree ("congregation_id","district_name");--> statement-breakpoint
CREATE INDEX "fiscal_years_year_name_idx" ON "fiscal_years" USING btree ("year_name");--> statement-breakpoint
CREATE INDEX "groups_congregation_id_idx" ON "groups" USING btree ("congregation_id");--> statement-breakpoint
CREATE UNIQUE INDEX "groups_congregation_id_group_name_unique" ON "groups" USING btree ("congregation_id","group_name");--> statement-breakpoint
CREATE INDEX "journal_entries_transaction_date_idx" ON "journal_entries" USING btree ("transaction_date");--> statement-breakpoint
CREATE INDEX "journal_entries_account_id_idx" ON "journal_entries" USING btree ("account_id");--> statement-breakpoint
CREATE INDEX "journal_entries_congregation_id_idx" ON "journal_entries" USING btree ("congregation_id");--> statement-breakpoint
CREATE INDEX "journal_entries_journal_no_idx" ON "journal_entries" USING btree ("journal_no");--> statement-breakpoint
CREATE INDEX "journal_entries_line_number_idx" ON "journal_entries" USING btree ("line_number");--> statement-breakpoint
CREATE INDEX "journal_entries_reference_idx" ON "journal_entries" USING btree ("reference");--> statement-breakpoint
CREATE INDEX "ledger_accounts_name_idx" ON "ledger_accounts" USING btree ("name");--> statement-breakpoint
CREATE INDEX "ledger_accounts_account_type_idx" ON "ledger_accounts" USING btree ("account_type");--> statement-breakpoint
CREATE INDEX "ledger_accounts_parent_id_idx" ON "ledger_accounts" USING btree ("parent_id");--> statement-breakpoint
CREATE INDEX "ledger_accounts_congregation_id_idx" ON "ledger_accounts" USING btree ("congregation_id");--> statement-breakpoint
CREATE INDEX "ledger_accounts_active_idx" ON "ledger_accounts" USING btree ("active");--> statement-breakpoint
CREATE UNIQUE INDEX "ledger_accounts_congregation_id_account_no_unique" ON "ledger_accounts" USING btree ("congregation_id","account_no");--> statement-breakpoint
CREATE INDEX "receipt_details_header_id_idx" ON "receipt_details" USING btree ("header_id");--> statement-breakpoint
CREATE INDEX "receipt_details_contribution_account_id_idx" ON "receipt_details" USING btree ("contribution_account_id");--> statement-breakpoint
CREATE INDEX "receipt_details_bank_id_idx" ON "receipt_details" USING btree ("bank_id");--> statement-breakpoint
CREATE INDEX "receipt_header_posted_by_idx" ON "receipt_header" USING btree ("posted_by");--> statement-breakpoint
CREATE INDEX "receipt_header_congregation_id_idx" ON "receipt_header" USING btree ("congregation_id");--> statement-breakpoint
CREATE INDEX "receipt_header_receipt_no_idx" ON "receipt_header" USING btree ("receipt_no");--> statement-breakpoint
CREATE INDEX "receipt_header_contribution_date_idx" ON "receipt_header" USING btree ("contribution_date");--> statement-breakpoint
CREATE UNIQUE INDEX "roles_role_name_unique" ON "roles" USING btree ("role_name");--> statement-breakpoint
CREATE INDEX "services_congregation_id_idx" ON "services" USING btree ("congregation_id");--> statement-breakpoint
CREATE UNIQUE INDEX "services_congregation_id_service_name_unique" ON "services" USING btree ("congregation_id","name");--> statement-breakpoint
CREATE UNIQUE INDEX "sessions_token_hash_unique" ON "sessions" USING btree ("token_hash");--> statement-breakpoint
CREATE INDEX "sessions_user_id_idx" ON "sessions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "sessions_expires_at_idx" ON "sessions" USING btree ("expires_at");--> statement-breakpoint
CREATE UNIQUE INDEX "subaccounts_name_unique" ON "sub_accounts" USING btree ("name");--> statement-breakpoint
CREATE UNIQUE INDEX "users_user_id_congregation_unique" ON "users" USING btree ("user_id","congregation_id");--> statement-breakpoint
CREATE INDEX "users_district_id_idx" ON "users" USING btree ("district_id");--> statement-breakpoint
CREATE INDEX "users_congregation_id_idx" ON "users" USING btree ("congregation_id");--> statement-breakpoint
CREATE INDEX "users_role_id_idx" ON "users" USING btree ("role_id");