CREATE TABLE "bank_postings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bank_postings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"transaction_date" date NOT NULL,
	"bank_id" integer NOT NULL,
	"dc" "line_dc" NOT NULL,
	"amount" numeric NOT NULL,
	"reference" varchar(255) NOT NULL,
	"counter_account_id" integer,
	"cleared" boolean DEFAULT false,
	"cleared_at" date,
	"narration" varchar(255),
	"source_type" varchar(50),
	"source_id" varchar(50),
	"congregation_id" integer NOT NULL,
	"deleted_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "bank_postings_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
ALTER TABLE "bank_postings" ADD CONSTRAINT "bank_postings_bank_id_ledger_accounts_id_fk" FOREIGN KEY ("bank_id") REFERENCES "public"."ledger_accounts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bank_postings" ADD CONSTRAINT "bank_postings_counter_account_id_ledger_accounts_id_fk" FOREIGN KEY ("counter_account_id") REFERENCES "public"."ledger_accounts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bank_postings" ADD CONSTRAINT "bank_postings_congregation_id_congregations_id_fk" FOREIGN KEY ("congregation_id") REFERENCES "public"."congregations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "bank_postings_bank_id_idx" ON "bank_postings" USING btree ("bank_id");--> statement-breakpoint
CREATE INDEX "bank_postings_transaction_date_idx" ON "bank_postings" USING btree ("transaction_date");--> statement-breakpoint
CREATE INDEX "bank_postings_reference_idx" ON "bank_postings" USING btree ("reference");