CREATE TYPE "public"."fund_requisition_status_enum" AS ENUM('pending', 'approved', 'rejected');--> statement-breakpoint
CREATE TYPE "public"."fund_requisition_type_enum" AS ENUM('group', 'district', 'church');--> statement-breakpoint
CREATE TABLE "church_requisition_categories" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "church_requisition_categories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(255) NOT NULL,
	"congregation_id" integer NOT NULL,
	"deleted_at" timestamp,
	CONSTRAINT "church_requisition_categories_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
CREATE TABLE "fund_requisitions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fund_requisitions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"requisition_no" integer NOT NULL,
	"requisition_date" date NOT NULL,
	"request_type" "fund_requisition_type_enum" NOT NULL,
	"district_id" integer,
	"group_id" integer,
	"purpose" varchar(255) NOT NULL,
	"status" "fund_requisition_status_enum" DEFAULT 'pending' NOT NULL,
	"amount_requested" numeric(10, 2) NOT NULL,
	"amount_approved" numeric(10, 2) NOT NULL,
	"requested_by" integer,
	"approved_by" integer,
	"approved_date" date,
	"dont_deduct" boolean DEFAULT false NOT NULL,
	"rejection_reason" varchar(255),
	"congregation_id" integer NOT NULL,
	"deleted_at" timestamp,
	CONSTRAINT "fund_requisitions_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
ALTER TABLE "bank_postings" ALTER COLUMN "amount" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "church_requisition_categories" ADD CONSTRAINT "church_requisition_categories_congregation_id_congregations_id_fk" FOREIGN KEY ("congregation_id") REFERENCES "public"."congregations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fund_requisitions" ADD CONSTRAINT "fund_requisitions_district_id_districts_id_fk" FOREIGN KEY ("district_id") REFERENCES "public"."districts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fund_requisitions" ADD CONSTRAINT "fund_requisitions_group_id_groups_id_fk" FOREIGN KEY ("group_id") REFERENCES "public"."groups"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fund_requisitions" ADD CONSTRAINT "fund_requisitions_requested_by_users_id_fk" FOREIGN KEY ("requested_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fund_requisitions" ADD CONSTRAINT "fund_requisitions_approved_by_users_id_fk" FOREIGN KEY ("approved_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fund_requisitions" ADD CONSTRAINT "fund_requisitions_congregation_id_congregations_id_fk" FOREIGN KEY ("congregation_id") REFERENCES "public"."congregations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "fund_requisitions_requisition_no_idx" ON "fund_requisitions" USING btree ("requisition_no");--> statement-breakpoint
CREATE INDEX "fund_requisitions_requisition_date_idx" ON "fund_requisitions" USING btree ("requisition_date");--> statement-breakpoint
CREATE INDEX "fund_requisitions_request_type_idx" ON "fund_requisitions" USING btree ("request_type");--> statement-breakpoint
CREATE INDEX "fund_requisitions_status_idx" ON "fund_requisitions" USING btree ("status");--> statement-breakpoint
CREATE INDEX "fund_requisitions_congregation_id_idx" ON "fund_requisitions" USING btree ("congregation_id");