CREATE TABLE "mmfs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mmfs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"transaction_date" date NOT NULL,
	"request_type" "fund_requisition_type_enum" NOT NULL,
	"group_id" integer,
	"district_id" integer,
	"dc" "line_dc" NOT NULL,
	"amount" numeric(10, 2) NOT NULL,
	"bank_id" integer,
	"sub_account_id" integer,
	"reference" varchar(255),
	"narration" varchar(255),
	"source_type" varchar(50),
	"source_id" varchar(50),
	"congregation_id" integer NOT NULL,
	"deleted_at" timestamp,
	CONSTRAINT "mmfs_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
ALTER TABLE "mmfs" ADD CONSTRAINT "mmfs_group_id_groups_id_fk" FOREIGN KEY ("group_id") REFERENCES "public"."groups"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mmfs" ADD CONSTRAINT "mmfs_district_id_districts_id_fk" FOREIGN KEY ("district_id") REFERENCES "public"."districts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mmfs" ADD CONSTRAINT "mmfs_bank_id_ledger_accounts_id_fk" FOREIGN KEY ("bank_id") REFERENCES "public"."ledger_accounts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mmfs" ADD CONSTRAINT "mmfs_sub_account_id_sub_accounts_id_fk" FOREIGN KEY ("sub_account_id") REFERENCES "public"."sub_accounts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mmfs" ADD CONSTRAINT "mmfs_congregation_id_congregations_id_fk" FOREIGN KEY ("congregation_id") REFERENCES "public"."congregations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "mmfs_transaction_date_idx" ON "mmfs" USING btree ("transaction_date");--> statement-breakpoint
CREATE INDEX "mmfs_reference_idx" ON "mmfs" USING btree ("reference");