CREATE TYPE "public"."expense_type_enum" AS ENUM('church', 'group', 'district');--> statement-breakpoint
CREATE TABLE "expenses_detail" (
	"id" varchar PRIMARY KEY NOT NULL,
	"expense_id" integer,
	"account_id" integer,
	"description" varchar(255) NOT NULL,
	"amount" numeric(10, 2) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "expenses_header" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "expenses_header_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"expense_date" date NOT NULL,
	"voucher_no" integer NOT NULL,
	"expense_type" "expense_type_enum" NOT NULL,
	"group_id" integer,
	"district_id" integer,
	"payment_method" "payment_method_enum" NOT NULL,
	"reference" varchar,
	"bank_id" integer,
	"crediting_account_id" integer,
	"requisition_id" integer,
	"status" "fund_requisition_status_enum" DEFAULT 'pending' NOT NULL,
	"congregation_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp,
	CONSTRAINT "expenses_header_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
CREATE TABLE "petty_cash" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "petty_cash_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"receipt_no" integer,
	"transaction_date" date NOT NULL,
	"amount" numeric(10, 2) NOT NULL,
	"dc" "line_dc" NOT NULL,
	"is_receipt" boolean DEFAULT false NOT NULL,
	"bank_id" integer,
	"reference" varchar(255),
	"narration" varchar(255),
	"source_type" varchar(50),
	"source_id" varchar(50),
	"congregation_id" integer NOT NULL,
	"deleted_at" timestamp,
	CONSTRAINT "petty_cash_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
ALTER TABLE "expenses_detail" ADD CONSTRAINT "expenses_detail_expense_id_expenses_header_id_fk" FOREIGN KEY ("expense_id") REFERENCES "public"."expenses_header"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expenses_detail" ADD CONSTRAINT "expenses_detail_account_id_ledger_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."ledger_accounts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expenses_header" ADD CONSTRAINT "expenses_header_group_id_groups_id_fk" FOREIGN KEY ("group_id") REFERENCES "public"."groups"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expenses_header" ADD CONSTRAINT "expenses_header_district_id_districts_id_fk" FOREIGN KEY ("district_id") REFERENCES "public"."districts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expenses_header" ADD CONSTRAINT "expenses_header_bank_id_ledger_accounts_id_fk" FOREIGN KEY ("bank_id") REFERENCES "public"."ledger_accounts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expenses_header" ADD CONSTRAINT "expenses_header_crediting_account_id_ledger_accounts_id_fk" FOREIGN KEY ("crediting_account_id") REFERENCES "public"."ledger_accounts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expenses_header" ADD CONSTRAINT "expenses_header_requisition_id_fund_requisitions_id_fk" FOREIGN KEY ("requisition_id") REFERENCES "public"."fund_requisitions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expenses_header" ADD CONSTRAINT "expenses_header_congregation_id_congregations_id_fk" FOREIGN KEY ("congregation_id") REFERENCES "public"."congregations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "petty_cash" ADD CONSTRAINT "petty_cash_bank_id_ledger_accounts_id_fk" FOREIGN KEY ("bank_id") REFERENCES "public"."ledger_accounts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "petty_cash" ADD CONSTRAINT "petty_cash_congregation_id_congregations_id_fk" FOREIGN KEY ("congregation_id") REFERENCES "public"."congregations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "expenses_detail_expense_id_idx" ON "expenses_detail" USING btree ("expense_id");--> statement-breakpoint
CREATE INDEX "expenses_detail_account_id_idx" ON "expenses_detail" USING btree ("account_id");--> statement-breakpoint
CREATE INDEX "expenses_header_expense_date_idx" ON "expenses_header" USING btree ("expense_date");--> statement-breakpoint
CREATE INDEX "expenses_header_voucher_no_idx" ON "expenses_header" USING btree ("voucher_no");--> statement-breakpoint
CREATE INDEX "expenses_header_expense_type_idx" ON "expenses_header" USING btree ("expense_type");--> statement-breakpoint
CREATE INDEX "expenses_header_group_id_idx" ON "expenses_header" USING btree ("group_id");--> statement-breakpoint
CREATE INDEX "expenses_header_district_id_idx" ON "expenses_header" USING btree ("district_id");--> statement-breakpoint
CREATE INDEX "expenses_header_reference_idx" ON "expenses_header" USING btree ("reference");--> statement-breakpoint
CREATE INDEX "expenses_header_status_idx" ON "expenses_header" USING btree ("status");--> statement-breakpoint
CREATE INDEX "expenses_header_congregation_id_idx" ON "expenses_header" USING btree ("congregation_id");--> statement-breakpoint
CREATE INDEX "petty_cash_transaction_date_idx" ON "petty_cash" USING btree ("transaction_date");--> statement-breakpoint
CREATE INDEX "petty_cash_receipt_no_idx" ON "petty_cash" USING btree ("receipt_no");--> statement-breakpoint
CREATE INDEX "petty_cash_reference_idx" ON "petty_cash" USING btree ("reference");--> statement-breakpoint
CREATE INDEX "petty_cash_congregation_id_idx" ON "petty_cash" USING btree ("congregation_id");