/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authedRouteRouteImport } from './routes/(authed)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authedFinanceRouteRouteImport } from './routes/(authed)/finance.route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as authedFinanceDashboardRouteImport } from './routes/(authed)/finance.dashboard'

const authedRouteRoute = authedRouteRouteImport.update({
  id: '/(authed)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authedFinanceRouteRoute = authedFinanceRouteRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => authedRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authedFinanceDashboardRoute = authedFinanceDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => authedFinanceRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/finance': typeof authedFinanceRouteRouteWithChildren
  '/finance/dashboard': typeof authedFinanceDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/finance': typeof authedFinanceRouteRouteWithChildren
  '/finance/dashboard': typeof authedFinanceDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(authed)': typeof authedRouteRouteWithChildren
  '/(authed)/finance': typeof authedFinanceRouteRouteWithChildren
  '/(authed)/finance/dashboard': typeof authedFinanceDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/finance' | '/finance/dashboard' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/finance' | '/finance/dashboard' | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/(authed)'
    | '/(authed)/finance'
    | '/(authed)/finance/dashboard'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authedRouteRoute: typeof authedRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authed)': {
      id: '/(authed)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authed)/finance': {
      id: '/(authed)/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof authedFinanceRouteRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authed)/finance/dashboard': {
      id: '/(authed)/finance/dashboard'
      path: '/dashboard'
      fullPath: '/finance/dashboard'
      preLoaderRoute: typeof authedFinanceDashboardRouteImport
      parentRoute: typeof authedFinanceRouteRoute
    }
  }
}

interface authedFinanceRouteRouteChildren {
  authedFinanceDashboardRoute: typeof authedFinanceDashboardRoute
}

const authedFinanceRouteRouteChildren: authedFinanceRouteRouteChildren = {
  authedFinanceDashboardRoute: authedFinanceDashboardRoute,
}

const authedFinanceRouteRouteWithChildren =
  authedFinanceRouteRoute._addFileChildren(authedFinanceRouteRouteChildren)

interface authedRouteRouteChildren {
  authedFinanceRouteRoute: typeof authedFinanceRouteRouteWithChildren
}

const authedRouteRouteChildren: authedRouteRouteChildren = {
  authedFinanceRouteRoute: authedFinanceRouteRouteWithChildren,
}

const authedRouteRouteWithChildren = authedRouteRoute._addFileChildren(
  authedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authedRouteRoute: authedRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
