/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authedRouteRouteImport } from './routes/(authed)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authChangePasswordRouteImport } from './routes/(auth)/change-password'
import { Route as authedFinanceRouteRouteImport } from './routes/(authed)/finance.route'
import { Route as authedFinanceDashboardRouteImport } from './routes/(authed)/finance.dashboard'
import { Route as authedFinanceChartOfAccountsRouteImport } from './routes/(authed)/finance.chart-of-accounts'
import { Route as authedFinanceReceiptsRouteRouteImport } from './routes/(authed)/finance.receipts.route'
import { Route as authedFinanceReceiptsIndexRouteImport } from './routes/(authed)/finance.receipts.index'
import { Route as authedFinanceReceiptsNewRouteImport } from './routes/(authed)/finance.receipts.new'
import { Route as authedFinanceReceiptsReceiptIdEditRouteImport } from './routes/(authed)/finance.receipts.$receiptId.edit'

const authedRouteRoute = authedRouteRouteImport.update({
  id: '/(authed)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authChangePasswordRoute = authChangePasswordRouteImport.update({
  id: '/(auth)/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authedFinanceRouteRoute = authedFinanceRouteRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedFinanceDashboardRoute = authedFinanceDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => authedFinanceRouteRoute,
} as any)
const authedFinanceChartOfAccountsRoute =
  authedFinanceChartOfAccountsRouteImport.update({
    id: '/chart-of-accounts',
    path: '/chart-of-accounts',
    getParentRoute: () => authedFinanceRouteRoute,
  } as any)
const authedFinanceReceiptsRouteRoute =
  authedFinanceReceiptsRouteRouteImport.update({
    id: '/receipts',
    path: '/receipts',
    getParentRoute: () => authedFinanceRouteRoute,
  } as any)
const authedFinanceReceiptsIndexRoute =
  authedFinanceReceiptsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authedFinanceReceiptsRouteRoute,
  } as any)
const authedFinanceReceiptsNewRoute =
  authedFinanceReceiptsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => authedFinanceReceiptsRouteRoute,
  } as any)
const authedFinanceReceiptsReceiptIdEditRoute =
  authedFinanceReceiptsReceiptIdEditRouteImport.update({
    id: '/$receiptId/edit',
    path: '/$receiptId/edit',
    getParentRoute: () => authedFinanceReceiptsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/finance': typeof authedFinanceRouteRouteWithChildren
  '/change-password': typeof authChangePasswordRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/finance/receipts': typeof authedFinanceReceiptsRouteRouteWithChildren
  '/finance/chart-of-accounts': typeof authedFinanceChartOfAccountsRoute
  '/finance/dashboard': typeof authedFinanceDashboardRoute
  '/finance/receipts/new': typeof authedFinanceReceiptsNewRoute
  '/finance/receipts/': typeof authedFinanceReceiptsIndexRoute
  '/finance/receipts/$receiptId/edit': typeof authedFinanceReceiptsReceiptIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/finance': typeof authedFinanceRouteRouteWithChildren
  '/change-password': typeof authChangePasswordRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/finance/chart-of-accounts': typeof authedFinanceChartOfAccountsRoute
  '/finance/dashboard': typeof authedFinanceDashboardRoute
  '/finance/receipts/new': typeof authedFinanceReceiptsNewRoute
  '/finance/receipts': typeof authedFinanceReceiptsIndexRoute
  '/finance/receipts/$receiptId/edit': typeof authedFinanceReceiptsReceiptIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(authed)': typeof authedRouteRouteWithChildren
  '/(authed)/finance': typeof authedFinanceRouteRouteWithChildren
  '/(auth)/change-password': typeof authChangePasswordRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(authed)/finance/receipts': typeof authedFinanceReceiptsRouteRouteWithChildren
  '/(authed)/finance/chart-of-accounts': typeof authedFinanceChartOfAccountsRoute
  '/(authed)/finance/dashboard': typeof authedFinanceDashboardRoute
  '/(authed)/finance/receipts/new': typeof authedFinanceReceiptsNewRoute
  '/(authed)/finance/receipts/': typeof authedFinanceReceiptsIndexRoute
  '/(authed)/finance/receipts/$receiptId/edit': typeof authedFinanceReceiptsReceiptIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/finance'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/finance/receipts'
    | '/finance/chart-of-accounts'
    | '/finance/dashboard'
    | '/finance/receipts/new'
    | '/finance/receipts/'
    | '/finance/receipts/$receiptId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/finance'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/finance/chart-of-accounts'
    | '/finance/dashboard'
    | '/finance/receipts/new'
    | '/finance/receipts'
    | '/finance/receipts/$receiptId/edit'
  id:
    | '__root__'
    | '/'
    | '/(authed)'
    | '/(authed)/finance'
    | '/(auth)/change-password'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(authed)/finance/receipts'
    | '/(authed)/finance/chart-of-accounts'
    | '/(authed)/finance/dashboard'
    | '/(authed)/finance/receipts/new'
    | '/(authed)/finance/receipts/'
    | '/(authed)/finance/receipts/$receiptId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authedRouteRoute: typeof authedRouteRouteWithChildren
  authChangePasswordRoute: typeof authChangePasswordRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authed)': {
      id: '/(authed)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/change-password': {
      id: '/(auth)/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof authChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authed)/finance': {
      id: '/(authed)/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof authedFinanceRouteRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/finance/dashboard': {
      id: '/(authed)/finance/dashboard'
      path: '/dashboard'
      fullPath: '/finance/dashboard'
      preLoaderRoute: typeof authedFinanceDashboardRouteImport
      parentRoute: typeof authedFinanceRouteRoute
    }
    '/(authed)/finance/chart-of-accounts': {
      id: '/(authed)/finance/chart-of-accounts'
      path: '/chart-of-accounts'
      fullPath: '/finance/chart-of-accounts'
      preLoaderRoute: typeof authedFinanceChartOfAccountsRouteImport
      parentRoute: typeof authedFinanceRouteRoute
    }
    '/(authed)/finance/receipts': {
      id: '/(authed)/finance/receipts'
      path: '/receipts'
      fullPath: '/finance/receipts'
      preLoaderRoute: typeof authedFinanceReceiptsRouteRouteImport
      parentRoute: typeof authedFinanceRouteRoute
    }
    '/(authed)/finance/receipts/': {
      id: '/(authed)/finance/receipts/'
      path: '/'
      fullPath: '/finance/receipts/'
      preLoaderRoute: typeof authedFinanceReceiptsIndexRouteImport
      parentRoute: typeof authedFinanceReceiptsRouteRoute
    }
    '/(authed)/finance/receipts/new': {
      id: '/(authed)/finance/receipts/new'
      path: '/new'
      fullPath: '/finance/receipts/new'
      preLoaderRoute: typeof authedFinanceReceiptsNewRouteImport
      parentRoute: typeof authedFinanceReceiptsRouteRoute
    }
    '/(authed)/finance/receipts/$receiptId/edit': {
      id: '/(authed)/finance/receipts/$receiptId/edit'
      path: '/$receiptId/edit'
      fullPath: '/finance/receipts/$receiptId/edit'
      preLoaderRoute: typeof authedFinanceReceiptsReceiptIdEditRouteImport
      parentRoute: typeof authedFinanceReceiptsRouteRoute
    }
  }
}

interface authedFinanceReceiptsRouteRouteChildren {
  authedFinanceReceiptsNewRoute: typeof authedFinanceReceiptsNewRoute
  authedFinanceReceiptsIndexRoute: typeof authedFinanceReceiptsIndexRoute
  authedFinanceReceiptsReceiptIdEditRoute: typeof authedFinanceReceiptsReceiptIdEditRoute
}

const authedFinanceReceiptsRouteRouteChildren: authedFinanceReceiptsRouteRouteChildren =
  {
    authedFinanceReceiptsNewRoute: authedFinanceReceiptsNewRoute,
    authedFinanceReceiptsIndexRoute: authedFinanceReceiptsIndexRoute,
    authedFinanceReceiptsReceiptIdEditRoute:
      authedFinanceReceiptsReceiptIdEditRoute,
  }

const authedFinanceReceiptsRouteRouteWithChildren =
  authedFinanceReceiptsRouteRoute._addFileChildren(
    authedFinanceReceiptsRouteRouteChildren,
  )

interface authedFinanceRouteRouteChildren {
  authedFinanceReceiptsRouteRoute: typeof authedFinanceReceiptsRouteRouteWithChildren
  authedFinanceChartOfAccountsRoute: typeof authedFinanceChartOfAccountsRoute
  authedFinanceDashboardRoute: typeof authedFinanceDashboardRoute
}

const authedFinanceRouteRouteChildren: authedFinanceRouteRouteChildren = {
  authedFinanceReceiptsRouteRoute: authedFinanceReceiptsRouteRouteWithChildren,
  authedFinanceChartOfAccountsRoute: authedFinanceChartOfAccountsRoute,
  authedFinanceDashboardRoute: authedFinanceDashboardRoute,
}

const authedFinanceRouteRouteWithChildren =
  authedFinanceRouteRoute._addFileChildren(authedFinanceRouteRouteChildren)

interface authedRouteRouteChildren {
  authedFinanceRouteRoute: typeof authedFinanceRouteRouteWithChildren
}

const authedRouteRouteChildren: authedRouteRouteChildren = {
  authedFinanceRouteRoute: authedFinanceRouteRouteWithChildren,
}

const authedRouteRouteWithChildren = authedRouteRoute._addFileChildren(
  authedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authedRouteRoute: authedRouteRouteWithChildren,
  authChangePasswordRoute: authChangePasswordRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
