/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authedRouteRouteImport } from './routes/(authed)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authChangePasswordRouteImport } from './routes/(auth)/change-password'
import { Route as authedFinanceRouteRouteImport } from './routes/(authed)/finance.route'
import { Route as ApiFundRequisitionsGetBalanceRouteImport } from './routes/api/fund-requisitions/get-balance'
import { Route as authedFinanceDashboardRouteImport } from './routes/(authed)/finance.dashboard'
import { Route as authedFinanceChartOfAccountsRouteImport } from './routes/(authed)/finance.chart-of-accounts'
import { Route as authedFinanceReceiptsRouteRouteImport } from './routes/(authed)/finance.receipts.route'
import { Route as authedFinancePettyCashRouteRouteImport } from './routes/(authed)/finance.petty-cash.route'
import { Route as authedFinanceFundRequisitionsRouteRouteImport } from './routes/(authed)/finance.fund-requisitions.route'
import { Route as authedFinanceExpensesRouteRouteImport } from './routes/(authed)/finance.expenses.route'
import { Route as authedFinanceBudgetsRouteRouteImport } from './routes/(authed)/finance.budgets.route'
import { Route as authedFinanceReceiptsIndexRouteImport } from './routes/(authed)/finance.receipts.index'
import { Route as authedFinancePettyCashIndexRouteImport } from './routes/(authed)/finance.petty-cash.index'
import { Route as authedFinanceJournalEntriesIndexRouteImport } from './routes/(authed)/finance.journal-entries.index'
import { Route as authedFinanceFundRequisitionsIndexRouteImport } from './routes/(authed)/finance.fund-requisitions.index'
import { Route as authedFinanceExpensesIndexRouteImport } from './routes/(authed)/finance.expenses.index'
import { Route as authedFinanceBudgetsIndexRouteImport } from './routes/(authed)/finance.budgets.index'
import { Route as authedFinanceReceiptsNewRouteImport } from './routes/(authed)/finance.receipts.new'
import { Route as authedFinancePettyCashNewRouteImport } from './routes/(authed)/finance.petty-cash.new'
import { Route as authedFinanceFundRequisitionsNewRouteImport } from './routes/(authed)/finance.fund-requisitions.new'
import { Route as authedFinanceExpensesNewRouteImport } from './routes/(authed)/finance.expenses.new'
import { Route as authedFinanceBudgetsNewRouteImport } from './routes/(authed)/finance.budgets.new'
import { Route as authedFinanceFundRequisitionsRequestIdRouteRouteImport } from './routes/(authed)/finance.fund-requisitions.$requestId.route'
import { Route as authedFinanceReceiptsReceiptIdEditRouteImport } from './routes/(authed)/finance.receipts.$receiptId.edit'
import { Route as authedFinancePettyCashPettyCashIdEditRouteImport } from './routes/(authed)/finance.petty-cash.$pettyCashId.edit'
import { Route as authedFinanceFundRequisitionsRequestIdEditRouteImport } from './routes/(authed)/finance.fund-requisitions.$requestId.edit'
import { Route as authedFinanceFundRequisitionsRequestIdActionRouteImport } from './routes/(authed)/finance.fund-requisitions.$requestId.action'
import { Route as authedFinanceExpensesExpenseIdEditRouteImport } from './routes/(authed)/finance.expenses.$expenseId.edit'
import { Route as authedFinanceBudgetsBudgetIdEditRouteImport } from './routes/(authed)/finance.budgets.$budgetId.edit'

const authedRouteRoute = authedRouteRouteImport.update({
  id: '/(authed)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authChangePasswordRoute = authChangePasswordRouteImport.update({
  id: '/(auth)/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authedFinanceRouteRoute = authedFinanceRouteRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => authedRouteRoute,
} as any)
const ApiFundRequisitionsGetBalanceRoute =
  ApiFundRequisitionsGetBalanceRouteImport.update({
    id: '/api/fund-requisitions/get-balance',
    path: '/api/fund-requisitions/get-balance',
    getParentRoute: () => rootRouteImport,
  } as any)
const authedFinanceDashboardRoute = authedFinanceDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => authedFinanceRouteRoute,
} as any)
const authedFinanceChartOfAccountsRoute =
  authedFinanceChartOfAccountsRouteImport.update({
    id: '/chart-of-accounts',
    path: '/chart-of-accounts',
    getParentRoute: () => authedFinanceRouteRoute,
  } as any)
const authedFinanceReceiptsRouteRoute =
  authedFinanceReceiptsRouteRouteImport.update({
    id: '/receipts',
    path: '/receipts',
    getParentRoute: () => authedFinanceRouteRoute,
  } as any)
const authedFinancePettyCashRouteRoute =
  authedFinancePettyCashRouteRouteImport.update({
    id: '/petty-cash',
    path: '/petty-cash',
    getParentRoute: () => authedFinanceRouteRoute,
  } as any)
const authedFinanceFundRequisitionsRouteRoute =
  authedFinanceFundRequisitionsRouteRouteImport.update({
    id: '/fund-requisitions',
    path: '/fund-requisitions',
    getParentRoute: () => authedFinanceRouteRoute,
  } as any)
const authedFinanceExpensesRouteRoute =
  authedFinanceExpensesRouteRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => authedFinanceRouteRoute,
  } as any)
const authedFinanceBudgetsRouteRoute =
  authedFinanceBudgetsRouteRouteImport.update({
    id: '/budgets',
    path: '/budgets',
    getParentRoute: () => authedFinanceRouteRoute,
  } as any)
const authedFinanceReceiptsIndexRoute =
  authedFinanceReceiptsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authedFinanceReceiptsRouteRoute,
  } as any)
const authedFinancePettyCashIndexRoute =
  authedFinancePettyCashIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authedFinancePettyCashRouteRoute,
  } as any)
const authedFinanceJournalEntriesIndexRoute =
  authedFinanceJournalEntriesIndexRouteImport.update({
    id: '/journal-entries/',
    path: '/journal-entries/',
    getParentRoute: () => authedFinanceRouteRoute,
  } as any)
const authedFinanceFundRequisitionsIndexRoute =
  authedFinanceFundRequisitionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authedFinanceFundRequisitionsRouteRoute,
  } as any)
const authedFinanceExpensesIndexRoute =
  authedFinanceExpensesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authedFinanceExpensesRouteRoute,
  } as any)
const authedFinanceBudgetsIndexRoute =
  authedFinanceBudgetsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authedFinanceBudgetsRouteRoute,
  } as any)
const authedFinanceReceiptsNewRoute =
  authedFinanceReceiptsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => authedFinanceReceiptsRouteRoute,
  } as any)
const authedFinancePettyCashNewRoute =
  authedFinancePettyCashNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => authedFinancePettyCashRouteRoute,
  } as any)
const authedFinanceFundRequisitionsNewRoute =
  authedFinanceFundRequisitionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => authedFinanceFundRequisitionsRouteRoute,
  } as any)
const authedFinanceExpensesNewRoute =
  authedFinanceExpensesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => authedFinanceExpensesRouteRoute,
  } as any)
const authedFinanceBudgetsNewRoute = authedFinanceBudgetsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => authedFinanceBudgetsRouteRoute,
} as any)
const authedFinanceFundRequisitionsRequestIdRouteRoute =
  authedFinanceFundRequisitionsRequestIdRouteRouteImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => authedFinanceFundRequisitionsRouteRoute,
  } as any)
const authedFinanceReceiptsReceiptIdEditRoute =
  authedFinanceReceiptsReceiptIdEditRouteImport.update({
    id: '/$receiptId/edit',
    path: '/$receiptId/edit',
    getParentRoute: () => authedFinanceReceiptsRouteRoute,
  } as any)
const authedFinancePettyCashPettyCashIdEditRoute =
  authedFinancePettyCashPettyCashIdEditRouteImport.update({
    id: '/$pettyCashId/edit',
    path: '/$pettyCashId/edit',
    getParentRoute: () => authedFinancePettyCashRouteRoute,
  } as any)
const authedFinanceFundRequisitionsRequestIdEditRoute =
  authedFinanceFundRequisitionsRequestIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => authedFinanceFundRequisitionsRequestIdRouteRoute,
  } as any)
const authedFinanceFundRequisitionsRequestIdActionRoute =
  authedFinanceFundRequisitionsRequestIdActionRouteImport.update({
    id: '/action',
    path: '/action',
    getParentRoute: () => authedFinanceFundRequisitionsRequestIdRouteRoute,
  } as any)
const authedFinanceExpensesExpenseIdEditRoute =
  authedFinanceExpensesExpenseIdEditRouteImport.update({
    id: '/$expenseId/edit',
    path: '/$expenseId/edit',
    getParentRoute: () => authedFinanceExpensesRouteRoute,
  } as any)
const authedFinanceBudgetsBudgetIdEditRoute =
  authedFinanceBudgetsBudgetIdEditRouteImport.update({
    id: '/$budgetId/edit',
    path: '/$budgetId/edit',
    getParentRoute: () => authedFinanceBudgetsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/finance': typeof authedFinanceRouteRouteWithChildren
  '/change-password': typeof authChangePasswordRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/finance/budgets': typeof authedFinanceBudgetsRouteRouteWithChildren
  '/finance/expenses': typeof authedFinanceExpensesRouteRouteWithChildren
  '/finance/fund-requisitions': typeof authedFinanceFundRequisitionsRouteRouteWithChildren
  '/finance/petty-cash': typeof authedFinancePettyCashRouteRouteWithChildren
  '/finance/receipts': typeof authedFinanceReceiptsRouteRouteWithChildren
  '/finance/chart-of-accounts': typeof authedFinanceChartOfAccountsRoute
  '/finance/dashboard': typeof authedFinanceDashboardRoute
  '/api/fund-requisitions/get-balance': typeof ApiFundRequisitionsGetBalanceRoute
  '/finance/fund-requisitions/$requestId': typeof authedFinanceFundRequisitionsRequestIdRouteRouteWithChildren
  '/finance/budgets/new': typeof authedFinanceBudgetsNewRoute
  '/finance/expenses/new': typeof authedFinanceExpensesNewRoute
  '/finance/fund-requisitions/new': typeof authedFinanceFundRequisitionsNewRoute
  '/finance/petty-cash/new': typeof authedFinancePettyCashNewRoute
  '/finance/receipts/new': typeof authedFinanceReceiptsNewRoute
  '/finance/budgets/': typeof authedFinanceBudgetsIndexRoute
  '/finance/expenses/': typeof authedFinanceExpensesIndexRoute
  '/finance/fund-requisitions/': typeof authedFinanceFundRequisitionsIndexRoute
  '/finance/journal-entries/': typeof authedFinanceJournalEntriesIndexRoute
  '/finance/petty-cash/': typeof authedFinancePettyCashIndexRoute
  '/finance/receipts/': typeof authedFinanceReceiptsIndexRoute
  '/finance/budgets/$budgetId/edit': typeof authedFinanceBudgetsBudgetIdEditRoute
  '/finance/expenses/$expenseId/edit': typeof authedFinanceExpensesExpenseIdEditRoute
  '/finance/fund-requisitions/$requestId/action': typeof authedFinanceFundRequisitionsRequestIdActionRoute
  '/finance/fund-requisitions/$requestId/edit': typeof authedFinanceFundRequisitionsRequestIdEditRoute
  '/finance/petty-cash/$pettyCashId/edit': typeof authedFinancePettyCashPettyCashIdEditRoute
  '/finance/receipts/$receiptId/edit': typeof authedFinanceReceiptsReceiptIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/finance': typeof authedFinanceRouteRouteWithChildren
  '/change-password': typeof authChangePasswordRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/finance/chart-of-accounts': typeof authedFinanceChartOfAccountsRoute
  '/finance/dashboard': typeof authedFinanceDashboardRoute
  '/api/fund-requisitions/get-balance': typeof ApiFundRequisitionsGetBalanceRoute
  '/finance/fund-requisitions/$requestId': typeof authedFinanceFundRequisitionsRequestIdRouteRouteWithChildren
  '/finance/budgets/new': typeof authedFinanceBudgetsNewRoute
  '/finance/expenses/new': typeof authedFinanceExpensesNewRoute
  '/finance/fund-requisitions/new': typeof authedFinanceFundRequisitionsNewRoute
  '/finance/petty-cash/new': typeof authedFinancePettyCashNewRoute
  '/finance/receipts/new': typeof authedFinanceReceiptsNewRoute
  '/finance/budgets': typeof authedFinanceBudgetsIndexRoute
  '/finance/expenses': typeof authedFinanceExpensesIndexRoute
  '/finance/fund-requisitions': typeof authedFinanceFundRequisitionsIndexRoute
  '/finance/journal-entries': typeof authedFinanceJournalEntriesIndexRoute
  '/finance/petty-cash': typeof authedFinancePettyCashIndexRoute
  '/finance/receipts': typeof authedFinanceReceiptsIndexRoute
  '/finance/budgets/$budgetId/edit': typeof authedFinanceBudgetsBudgetIdEditRoute
  '/finance/expenses/$expenseId/edit': typeof authedFinanceExpensesExpenseIdEditRoute
  '/finance/fund-requisitions/$requestId/action': typeof authedFinanceFundRequisitionsRequestIdActionRoute
  '/finance/fund-requisitions/$requestId/edit': typeof authedFinanceFundRequisitionsRequestIdEditRoute
  '/finance/petty-cash/$pettyCashId/edit': typeof authedFinancePettyCashPettyCashIdEditRoute
  '/finance/receipts/$receiptId/edit': typeof authedFinanceReceiptsReceiptIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(authed)': typeof authedRouteRouteWithChildren
  '/(authed)/finance': typeof authedFinanceRouteRouteWithChildren
  '/(auth)/change-password': typeof authChangePasswordRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(authed)/finance/budgets': typeof authedFinanceBudgetsRouteRouteWithChildren
  '/(authed)/finance/expenses': typeof authedFinanceExpensesRouteRouteWithChildren
  '/(authed)/finance/fund-requisitions': typeof authedFinanceFundRequisitionsRouteRouteWithChildren
  '/(authed)/finance/petty-cash': typeof authedFinancePettyCashRouteRouteWithChildren
  '/(authed)/finance/receipts': typeof authedFinanceReceiptsRouteRouteWithChildren
  '/(authed)/finance/chart-of-accounts': typeof authedFinanceChartOfAccountsRoute
  '/(authed)/finance/dashboard': typeof authedFinanceDashboardRoute
  '/api/fund-requisitions/get-balance': typeof ApiFundRequisitionsGetBalanceRoute
  '/(authed)/finance/fund-requisitions/$requestId': typeof authedFinanceFundRequisitionsRequestIdRouteRouteWithChildren
  '/(authed)/finance/budgets/new': typeof authedFinanceBudgetsNewRoute
  '/(authed)/finance/expenses/new': typeof authedFinanceExpensesNewRoute
  '/(authed)/finance/fund-requisitions/new': typeof authedFinanceFundRequisitionsNewRoute
  '/(authed)/finance/petty-cash/new': typeof authedFinancePettyCashNewRoute
  '/(authed)/finance/receipts/new': typeof authedFinanceReceiptsNewRoute
  '/(authed)/finance/budgets/': typeof authedFinanceBudgetsIndexRoute
  '/(authed)/finance/expenses/': typeof authedFinanceExpensesIndexRoute
  '/(authed)/finance/fund-requisitions/': typeof authedFinanceFundRequisitionsIndexRoute
  '/(authed)/finance/journal-entries/': typeof authedFinanceJournalEntriesIndexRoute
  '/(authed)/finance/petty-cash/': typeof authedFinancePettyCashIndexRoute
  '/(authed)/finance/receipts/': typeof authedFinanceReceiptsIndexRoute
  '/(authed)/finance/budgets/$budgetId/edit': typeof authedFinanceBudgetsBudgetIdEditRoute
  '/(authed)/finance/expenses/$expenseId/edit': typeof authedFinanceExpensesExpenseIdEditRoute
  '/(authed)/finance/fund-requisitions/$requestId/action': typeof authedFinanceFundRequisitionsRequestIdActionRoute
  '/(authed)/finance/fund-requisitions/$requestId/edit': typeof authedFinanceFundRequisitionsRequestIdEditRoute
  '/(authed)/finance/petty-cash/$pettyCashId/edit': typeof authedFinancePettyCashPettyCashIdEditRoute
  '/(authed)/finance/receipts/$receiptId/edit': typeof authedFinanceReceiptsReceiptIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/finance'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/finance/budgets'
    | '/finance/expenses'
    | '/finance/fund-requisitions'
    | '/finance/petty-cash'
    | '/finance/receipts'
    | '/finance/chart-of-accounts'
    | '/finance/dashboard'
    | '/api/fund-requisitions/get-balance'
    | '/finance/fund-requisitions/$requestId'
    | '/finance/budgets/new'
    | '/finance/expenses/new'
    | '/finance/fund-requisitions/new'
    | '/finance/petty-cash/new'
    | '/finance/receipts/new'
    | '/finance/budgets/'
    | '/finance/expenses/'
    | '/finance/fund-requisitions/'
    | '/finance/journal-entries/'
    | '/finance/petty-cash/'
    | '/finance/receipts/'
    | '/finance/budgets/$budgetId/edit'
    | '/finance/expenses/$expenseId/edit'
    | '/finance/fund-requisitions/$requestId/action'
    | '/finance/fund-requisitions/$requestId/edit'
    | '/finance/petty-cash/$pettyCashId/edit'
    | '/finance/receipts/$receiptId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/finance'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/finance/chart-of-accounts'
    | '/finance/dashboard'
    | '/api/fund-requisitions/get-balance'
    | '/finance/fund-requisitions/$requestId'
    | '/finance/budgets/new'
    | '/finance/expenses/new'
    | '/finance/fund-requisitions/new'
    | '/finance/petty-cash/new'
    | '/finance/receipts/new'
    | '/finance/budgets'
    | '/finance/expenses'
    | '/finance/fund-requisitions'
    | '/finance/journal-entries'
    | '/finance/petty-cash'
    | '/finance/receipts'
    | '/finance/budgets/$budgetId/edit'
    | '/finance/expenses/$expenseId/edit'
    | '/finance/fund-requisitions/$requestId/action'
    | '/finance/fund-requisitions/$requestId/edit'
    | '/finance/petty-cash/$pettyCashId/edit'
    | '/finance/receipts/$receiptId/edit'
  id:
    | '__root__'
    | '/'
    | '/(authed)'
    | '/(authed)/finance'
    | '/(auth)/change-password'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(authed)/finance/budgets'
    | '/(authed)/finance/expenses'
    | '/(authed)/finance/fund-requisitions'
    | '/(authed)/finance/petty-cash'
    | '/(authed)/finance/receipts'
    | '/(authed)/finance/chart-of-accounts'
    | '/(authed)/finance/dashboard'
    | '/api/fund-requisitions/get-balance'
    | '/(authed)/finance/fund-requisitions/$requestId'
    | '/(authed)/finance/budgets/new'
    | '/(authed)/finance/expenses/new'
    | '/(authed)/finance/fund-requisitions/new'
    | '/(authed)/finance/petty-cash/new'
    | '/(authed)/finance/receipts/new'
    | '/(authed)/finance/budgets/'
    | '/(authed)/finance/expenses/'
    | '/(authed)/finance/fund-requisitions/'
    | '/(authed)/finance/journal-entries/'
    | '/(authed)/finance/petty-cash/'
    | '/(authed)/finance/receipts/'
    | '/(authed)/finance/budgets/$budgetId/edit'
    | '/(authed)/finance/expenses/$expenseId/edit'
    | '/(authed)/finance/fund-requisitions/$requestId/action'
    | '/(authed)/finance/fund-requisitions/$requestId/edit'
    | '/(authed)/finance/petty-cash/$pettyCashId/edit'
    | '/(authed)/finance/receipts/$receiptId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authedRouteRoute: typeof authedRouteRouteWithChildren
  authChangePasswordRoute: typeof authChangePasswordRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  ApiFundRequisitionsGetBalanceRoute: typeof ApiFundRequisitionsGetBalanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authed)': {
      id: '/(authed)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/change-password': {
      id: '/(auth)/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof authChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authed)/finance': {
      id: '/(authed)/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof authedFinanceRouteRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/api/fund-requisitions/get-balance': {
      id: '/api/fund-requisitions/get-balance'
      path: '/api/fund-requisitions/get-balance'
      fullPath: '/api/fund-requisitions/get-balance'
      preLoaderRoute: typeof ApiFundRequisitionsGetBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authed)/finance/dashboard': {
      id: '/(authed)/finance/dashboard'
      path: '/dashboard'
      fullPath: '/finance/dashboard'
      preLoaderRoute: typeof authedFinanceDashboardRouteImport
      parentRoute: typeof authedFinanceRouteRoute
    }
    '/(authed)/finance/chart-of-accounts': {
      id: '/(authed)/finance/chart-of-accounts'
      path: '/chart-of-accounts'
      fullPath: '/finance/chart-of-accounts'
      preLoaderRoute: typeof authedFinanceChartOfAccountsRouteImport
      parentRoute: typeof authedFinanceRouteRoute
    }
    '/(authed)/finance/receipts': {
      id: '/(authed)/finance/receipts'
      path: '/receipts'
      fullPath: '/finance/receipts'
      preLoaderRoute: typeof authedFinanceReceiptsRouteRouteImport
      parentRoute: typeof authedFinanceRouteRoute
    }
    '/(authed)/finance/petty-cash': {
      id: '/(authed)/finance/petty-cash'
      path: '/petty-cash'
      fullPath: '/finance/petty-cash'
      preLoaderRoute: typeof authedFinancePettyCashRouteRouteImport
      parentRoute: typeof authedFinanceRouteRoute
    }
    '/(authed)/finance/fund-requisitions': {
      id: '/(authed)/finance/fund-requisitions'
      path: '/fund-requisitions'
      fullPath: '/finance/fund-requisitions'
      preLoaderRoute: typeof authedFinanceFundRequisitionsRouteRouteImport
      parentRoute: typeof authedFinanceRouteRoute
    }
    '/(authed)/finance/expenses': {
      id: '/(authed)/finance/expenses'
      path: '/expenses'
      fullPath: '/finance/expenses'
      preLoaderRoute: typeof authedFinanceExpensesRouteRouteImport
      parentRoute: typeof authedFinanceRouteRoute
    }
    '/(authed)/finance/budgets': {
      id: '/(authed)/finance/budgets'
      path: '/budgets'
      fullPath: '/finance/budgets'
      preLoaderRoute: typeof authedFinanceBudgetsRouteRouteImport
      parentRoute: typeof authedFinanceRouteRoute
    }
    '/(authed)/finance/receipts/': {
      id: '/(authed)/finance/receipts/'
      path: '/'
      fullPath: '/finance/receipts/'
      preLoaderRoute: typeof authedFinanceReceiptsIndexRouteImport
      parentRoute: typeof authedFinanceReceiptsRouteRoute
    }
    '/(authed)/finance/petty-cash/': {
      id: '/(authed)/finance/petty-cash/'
      path: '/'
      fullPath: '/finance/petty-cash/'
      preLoaderRoute: typeof authedFinancePettyCashIndexRouteImport
      parentRoute: typeof authedFinancePettyCashRouteRoute
    }
    '/(authed)/finance/journal-entries/': {
      id: '/(authed)/finance/journal-entries/'
      path: '/journal-entries'
      fullPath: '/finance/journal-entries/'
      preLoaderRoute: typeof authedFinanceJournalEntriesIndexRouteImport
      parentRoute: typeof authedFinanceRouteRoute
    }
    '/(authed)/finance/fund-requisitions/': {
      id: '/(authed)/finance/fund-requisitions/'
      path: '/'
      fullPath: '/finance/fund-requisitions/'
      preLoaderRoute: typeof authedFinanceFundRequisitionsIndexRouteImport
      parentRoute: typeof authedFinanceFundRequisitionsRouteRoute
    }
    '/(authed)/finance/expenses/': {
      id: '/(authed)/finance/expenses/'
      path: '/'
      fullPath: '/finance/expenses/'
      preLoaderRoute: typeof authedFinanceExpensesIndexRouteImport
      parentRoute: typeof authedFinanceExpensesRouteRoute
    }
    '/(authed)/finance/budgets/': {
      id: '/(authed)/finance/budgets/'
      path: '/'
      fullPath: '/finance/budgets/'
      preLoaderRoute: typeof authedFinanceBudgetsIndexRouteImport
      parentRoute: typeof authedFinanceBudgetsRouteRoute
    }
    '/(authed)/finance/receipts/new': {
      id: '/(authed)/finance/receipts/new'
      path: '/new'
      fullPath: '/finance/receipts/new'
      preLoaderRoute: typeof authedFinanceReceiptsNewRouteImport
      parentRoute: typeof authedFinanceReceiptsRouteRoute
    }
    '/(authed)/finance/petty-cash/new': {
      id: '/(authed)/finance/petty-cash/new'
      path: '/new'
      fullPath: '/finance/petty-cash/new'
      preLoaderRoute: typeof authedFinancePettyCashNewRouteImport
      parentRoute: typeof authedFinancePettyCashRouteRoute
    }
    '/(authed)/finance/fund-requisitions/new': {
      id: '/(authed)/finance/fund-requisitions/new'
      path: '/new'
      fullPath: '/finance/fund-requisitions/new'
      preLoaderRoute: typeof authedFinanceFundRequisitionsNewRouteImport
      parentRoute: typeof authedFinanceFundRequisitionsRouteRoute
    }
    '/(authed)/finance/expenses/new': {
      id: '/(authed)/finance/expenses/new'
      path: '/new'
      fullPath: '/finance/expenses/new'
      preLoaderRoute: typeof authedFinanceExpensesNewRouteImport
      parentRoute: typeof authedFinanceExpensesRouteRoute
    }
    '/(authed)/finance/budgets/new': {
      id: '/(authed)/finance/budgets/new'
      path: '/new'
      fullPath: '/finance/budgets/new'
      preLoaderRoute: typeof authedFinanceBudgetsNewRouteImport
      parentRoute: typeof authedFinanceBudgetsRouteRoute
    }
    '/(authed)/finance/fund-requisitions/$requestId': {
      id: '/(authed)/finance/fund-requisitions/$requestId'
      path: '/$requestId'
      fullPath: '/finance/fund-requisitions/$requestId'
      preLoaderRoute: typeof authedFinanceFundRequisitionsRequestIdRouteRouteImport
      parentRoute: typeof authedFinanceFundRequisitionsRouteRoute
    }
    '/(authed)/finance/receipts/$receiptId/edit': {
      id: '/(authed)/finance/receipts/$receiptId/edit'
      path: '/$receiptId/edit'
      fullPath: '/finance/receipts/$receiptId/edit'
      preLoaderRoute: typeof authedFinanceReceiptsReceiptIdEditRouteImport
      parentRoute: typeof authedFinanceReceiptsRouteRoute
    }
    '/(authed)/finance/petty-cash/$pettyCashId/edit': {
      id: '/(authed)/finance/petty-cash/$pettyCashId/edit'
      path: '/$pettyCashId/edit'
      fullPath: '/finance/petty-cash/$pettyCashId/edit'
      preLoaderRoute: typeof authedFinancePettyCashPettyCashIdEditRouteImport
      parentRoute: typeof authedFinancePettyCashRouteRoute
    }
    '/(authed)/finance/fund-requisitions/$requestId/edit': {
      id: '/(authed)/finance/fund-requisitions/$requestId/edit'
      path: '/edit'
      fullPath: '/finance/fund-requisitions/$requestId/edit'
      preLoaderRoute: typeof authedFinanceFundRequisitionsRequestIdEditRouteImport
      parentRoute: typeof authedFinanceFundRequisitionsRequestIdRouteRoute
    }
    '/(authed)/finance/fund-requisitions/$requestId/action': {
      id: '/(authed)/finance/fund-requisitions/$requestId/action'
      path: '/action'
      fullPath: '/finance/fund-requisitions/$requestId/action'
      preLoaderRoute: typeof authedFinanceFundRequisitionsRequestIdActionRouteImport
      parentRoute: typeof authedFinanceFundRequisitionsRequestIdRouteRoute
    }
    '/(authed)/finance/expenses/$expenseId/edit': {
      id: '/(authed)/finance/expenses/$expenseId/edit'
      path: '/$expenseId/edit'
      fullPath: '/finance/expenses/$expenseId/edit'
      preLoaderRoute: typeof authedFinanceExpensesExpenseIdEditRouteImport
      parentRoute: typeof authedFinanceExpensesRouteRoute
    }
    '/(authed)/finance/budgets/$budgetId/edit': {
      id: '/(authed)/finance/budgets/$budgetId/edit'
      path: '/$budgetId/edit'
      fullPath: '/finance/budgets/$budgetId/edit'
      preLoaderRoute: typeof authedFinanceBudgetsBudgetIdEditRouteImport
      parentRoute: typeof authedFinanceBudgetsRouteRoute
    }
  }
}

interface authedFinanceBudgetsRouteRouteChildren {
  authedFinanceBudgetsNewRoute: typeof authedFinanceBudgetsNewRoute
  authedFinanceBudgetsIndexRoute: typeof authedFinanceBudgetsIndexRoute
  authedFinanceBudgetsBudgetIdEditRoute: typeof authedFinanceBudgetsBudgetIdEditRoute
}

const authedFinanceBudgetsRouteRouteChildren: authedFinanceBudgetsRouteRouteChildren =
  {
    authedFinanceBudgetsNewRoute: authedFinanceBudgetsNewRoute,
    authedFinanceBudgetsIndexRoute: authedFinanceBudgetsIndexRoute,
    authedFinanceBudgetsBudgetIdEditRoute:
      authedFinanceBudgetsBudgetIdEditRoute,
  }

const authedFinanceBudgetsRouteRouteWithChildren =
  authedFinanceBudgetsRouteRoute._addFileChildren(
    authedFinanceBudgetsRouteRouteChildren,
  )

interface authedFinanceExpensesRouteRouteChildren {
  authedFinanceExpensesNewRoute: typeof authedFinanceExpensesNewRoute
  authedFinanceExpensesIndexRoute: typeof authedFinanceExpensesIndexRoute
  authedFinanceExpensesExpenseIdEditRoute: typeof authedFinanceExpensesExpenseIdEditRoute
}

const authedFinanceExpensesRouteRouteChildren: authedFinanceExpensesRouteRouteChildren =
  {
    authedFinanceExpensesNewRoute: authedFinanceExpensesNewRoute,
    authedFinanceExpensesIndexRoute: authedFinanceExpensesIndexRoute,
    authedFinanceExpensesExpenseIdEditRoute:
      authedFinanceExpensesExpenseIdEditRoute,
  }

const authedFinanceExpensesRouteRouteWithChildren =
  authedFinanceExpensesRouteRoute._addFileChildren(
    authedFinanceExpensesRouteRouteChildren,
  )

interface authedFinanceFundRequisitionsRequestIdRouteRouteChildren {
  authedFinanceFundRequisitionsRequestIdActionRoute: typeof authedFinanceFundRequisitionsRequestIdActionRoute
  authedFinanceFundRequisitionsRequestIdEditRoute: typeof authedFinanceFundRequisitionsRequestIdEditRoute
}

const authedFinanceFundRequisitionsRequestIdRouteRouteChildren: authedFinanceFundRequisitionsRequestIdRouteRouteChildren =
  {
    authedFinanceFundRequisitionsRequestIdActionRoute:
      authedFinanceFundRequisitionsRequestIdActionRoute,
    authedFinanceFundRequisitionsRequestIdEditRoute:
      authedFinanceFundRequisitionsRequestIdEditRoute,
  }

const authedFinanceFundRequisitionsRequestIdRouteRouteWithChildren =
  authedFinanceFundRequisitionsRequestIdRouteRoute._addFileChildren(
    authedFinanceFundRequisitionsRequestIdRouteRouteChildren,
  )

interface authedFinanceFundRequisitionsRouteRouteChildren {
  authedFinanceFundRequisitionsRequestIdRouteRoute: typeof authedFinanceFundRequisitionsRequestIdRouteRouteWithChildren
  authedFinanceFundRequisitionsNewRoute: typeof authedFinanceFundRequisitionsNewRoute
  authedFinanceFundRequisitionsIndexRoute: typeof authedFinanceFundRequisitionsIndexRoute
}

const authedFinanceFundRequisitionsRouteRouteChildren: authedFinanceFundRequisitionsRouteRouteChildren =
  {
    authedFinanceFundRequisitionsRequestIdRouteRoute:
      authedFinanceFundRequisitionsRequestIdRouteRouteWithChildren,
    authedFinanceFundRequisitionsNewRoute:
      authedFinanceFundRequisitionsNewRoute,
    authedFinanceFundRequisitionsIndexRoute:
      authedFinanceFundRequisitionsIndexRoute,
  }

const authedFinanceFundRequisitionsRouteRouteWithChildren =
  authedFinanceFundRequisitionsRouteRoute._addFileChildren(
    authedFinanceFundRequisitionsRouteRouteChildren,
  )

interface authedFinancePettyCashRouteRouteChildren {
  authedFinancePettyCashNewRoute: typeof authedFinancePettyCashNewRoute
  authedFinancePettyCashIndexRoute: typeof authedFinancePettyCashIndexRoute
  authedFinancePettyCashPettyCashIdEditRoute: typeof authedFinancePettyCashPettyCashIdEditRoute
}

const authedFinancePettyCashRouteRouteChildren: authedFinancePettyCashRouteRouteChildren =
  {
    authedFinancePettyCashNewRoute: authedFinancePettyCashNewRoute,
    authedFinancePettyCashIndexRoute: authedFinancePettyCashIndexRoute,
    authedFinancePettyCashPettyCashIdEditRoute:
      authedFinancePettyCashPettyCashIdEditRoute,
  }

const authedFinancePettyCashRouteRouteWithChildren =
  authedFinancePettyCashRouteRoute._addFileChildren(
    authedFinancePettyCashRouteRouteChildren,
  )

interface authedFinanceReceiptsRouteRouteChildren {
  authedFinanceReceiptsNewRoute: typeof authedFinanceReceiptsNewRoute
  authedFinanceReceiptsIndexRoute: typeof authedFinanceReceiptsIndexRoute
  authedFinanceReceiptsReceiptIdEditRoute: typeof authedFinanceReceiptsReceiptIdEditRoute
}

const authedFinanceReceiptsRouteRouteChildren: authedFinanceReceiptsRouteRouteChildren =
  {
    authedFinanceReceiptsNewRoute: authedFinanceReceiptsNewRoute,
    authedFinanceReceiptsIndexRoute: authedFinanceReceiptsIndexRoute,
    authedFinanceReceiptsReceiptIdEditRoute:
      authedFinanceReceiptsReceiptIdEditRoute,
  }

const authedFinanceReceiptsRouteRouteWithChildren =
  authedFinanceReceiptsRouteRoute._addFileChildren(
    authedFinanceReceiptsRouteRouteChildren,
  )

interface authedFinanceRouteRouteChildren {
  authedFinanceBudgetsRouteRoute: typeof authedFinanceBudgetsRouteRouteWithChildren
  authedFinanceExpensesRouteRoute: typeof authedFinanceExpensesRouteRouteWithChildren
  authedFinanceFundRequisitionsRouteRoute: typeof authedFinanceFundRequisitionsRouteRouteWithChildren
  authedFinancePettyCashRouteRoute: typeof authedFinancePettyCashRouteRouteWithChildren
  authedFinanceReceiptsRouteRoute: typeof authedFinanceReceiptsRouteRouteWithChildren
  authedFinanceChartOfAccountsRoute: typeof authedFinanceChartOfAccountsRoute
  authedFinanceDashboardRoute: typeof authedFinanceDashboardRoute
  authedFinanceJournalEntriesIndexRoute: typeof authedFinanceJournalEntriesIndexRoute
}

const authedFinanceRouteRouteChildren: authedFinanceRouteRouteChildren = {
  authedFinanceBudgetsRouteRoute: authedFinanceBudgetsRouteRouteWithChildren,
  authedFinanceExpensesRouteRoute: authedFinanceExpensesRouteRouteWithChildren,
  authedFinanceFundRequisitionsRouteRoute:
    authedFinanceFundRequisitionsRouteRouteWithChildren,
  authedFinancePettyCashRouteRoute:
    authedFinancePettyCashRouteRouteWithChildren,
  authedFinanceReceiptsRouteRoute: authedFinanceReceiptsRouteRouteWithChildren,
  authedFinanceChartOfAccountsRoute: authedFinanceChartOfAccountsRoute,
  authedFinanceDashboardRoute: authedFinanceDashboardRoute,
  authedFinanceJournalEntriesIndexRoute: authedFinanceJournalEntriesIndexRoute,
}

const authedFinanceRouteRouteWithChildren =
  authedFinanceRouteRoute._addFileChildren(authedFinanceRouteRouteChildren)

interface authedRouteRouteChildren {
  authedFinanceRouteRoute: typeof authedFinanceRouteRouteWithChildren
}

const authedRouteRouteChildren: authedRouteRouteChildren = {
  authedFinanceRouteRoute: authedFinanceRouteRouteWithChildren,
}

const authedRouteRouteWithChildren = authedRouteRoute._addFileChildren(
  authedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authedRouteRoute: authedRouteRouteWithChildren,
  authChangePasswordRoute: authChangePasswordRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  ApiFundRequisitionsGetBalanceRoute: ApiFundRequisitionsGetBalanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
